# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: The R Programming Language
author: Dr George Farmer & Dr Martyn McFarquhar
copyright: "2026"
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/PCHN63101-Advanced-Data-Skills/R-Programming-Language  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

#binder:
#  repo: "https://github.com/rocker-org/binder"
#  ref: "master" 

launch_buttons:
  thebe: true

#thebe:
#  use_thebe: true
#  kernel_name: ir
  #repository_url: https://github.com/rocker-org/binder
  #branch: master

thebe:
  use_thebe: true
  binder:
    repo: "https://github.com/rocker-org/binder"
    ref: "main"
    binder_url: "https://mybinder.org"
  kernel_name: "ir"
